version: '3.8'

services:
  postgresdb:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: hsl_postgresdb_dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev_admin
      POSTGRES_DB: hslbikeapp_dev
    volumes:
      - pgdatadev:/var/lib/postgresql/data

volumes:
  pgdatadev:
